### ISSUE TITLE
Available Tokens not shown for KAVA delegate dialogue box 

### ISSUE THREAD

**Issue by thecryptodrive** [ping-pub/explorer#136]
![image](https://user-images.githubusercontent.com/22358264/169201885-f1c75793-7577-4f03-a327-ed47a03ce38d.png)
Image above explains it.

Ricardo | Notional

**Comment by thecryptodrive** [comment]
Might also want to rename to "Available Tokens" to be plural

**Comment by liangping** [comment]
@thecryptodrive I check on my side, no problem found.  could be network issue.

From your screen shot, you are not visit the latest version. if you run your own instance, please upgrade
