### ISSUE TITLE
Mismatch error when claiming Regen Validator Commission

### ISSUE THREAD

**Issue by thecryptodrive** [ping-pub/explorer#137]
![image](https://user-images.githubusercontent.com/22358264/169202063-89d0b5e6-ef9d-417f-b0cd-bb5f4360ee33.png)

Ricardo | Notional

**Comment by liangping** [comment]
This issue is often been seen when there are backlog of transactions on endpoint server. 
You just need wait for a while or switch to another endpoint if there are.
