### ISSUE TITLE
README docs refer to a config/app.toml -- there is no config folder nor such a file

### ISSUE THREAD

**Issue by njmurarka** [ping-pub/explorer#148]
I am trying to configure this to work for my chain but I must be missing something.

I cloned the repo. Now where is app.toml and where is this config folder? Do I need to create this?

What is the API for? Isn't PingPub just configured to talk to chains and display the relevant data? If so, what is app.toml for?

**Comment by liangping** [comment]
`config/app.toml` is on your fullnode of blockchain instance, which is used to enable api service on your server.

**Comment by njmurarka** [comment]
Thanks. Understood. I did not realize the doc was referring to my own chain's config, but now that makes sense. I might suggest annotating that in the docs.

**Comment by liangping** [comment]
Welcome to make a PR for the docs

**Comment by njmurarka** [comment]
Done!
