### ISSUE TITLE
comdex claiming fails

### ISSUE THREAD

**Issue by Creamers158** [ping-pub/explorer#156]
When trying to claim both commissions and rewards as a validator using ping.pub explorer it fails on Comdex.
(Works fine on other chains)

Withdraw commission (as validator so both commissions and rewards are claimed)
Choose usb ledger
Confirm on ledger

Result is 
Error: rpc error: code = InvalidArgument desc = must declare at least one event to search: invalid request
![comdexclaim](https://user-images.githubusercontent.com/6506666/176940086-6db9101e-22d5-41e5-8ac8-f8dd6f4d1db1.png)

**Comment by liangping** [comment]
This is a confirmed issue on blockchain side. it shows when sending tx in sync mode.
