### ISSUE TITLE
Make default validators sort algorithm randomized

### ISSUE THREAD

**Issue by angrymouse** [ping-pub/explorer#164]
We should consider randomizing validator results in "Staking" tab.
For now, validator sorted by voting power by default. It leads to centralization of networks to top 10 validators.
If we consider doing randomization of results by defaut (you still can sort by voting power when you explicitly want it, via clicking on "Voting power" param), then people who delegate to top 10 will maybe delegate to other validators.
I can make PR, but I need to know thoughts of developers and community about it.

**Comment by liangping** [comment]
Sounds reasonable,

**Comment by liangping** [comment]
@angrymouse This feature has been implemented in https://github.com/ping-pub/explorer/commit/32364a8cfb6f504c08f9215aa91ba36817d1cc63, but only applied when the validator is not specified.

**Comment by angrymouse** [comment]
Thank you!
