### ISSUE TITLE
When the evmos chain is extended with keplr, the transfer is successful in the extension, but the transfer is wrong in the dapp (https://ping.pub)

### ISSUE THREAD

**Issue by YouquanWang** [ping-pub/explorer#169]
When the evmos chain is extended with keplr, the transfer is successful in the extension, but the transfer is wrong in the dapp (https://ping.pub)
Error: pubKey does not match signer address evmos1z9zk7an7zf8k7t5407yzsjky0n0scmr6hrzwu0 with signer index: 0: invalid pubkey

**Comment by liangping** [comment]
You can sign with ledger for now.

**Comment by YouquanWang** [comment]
can you send me the link

**Comment by liangping** [comment]
works with both Keplr and Ledger now
