### ISSUE TITLE
stuck coins

### ISSUE THREAD

**Issue by cecicece** [ping-pub/explorer#177]
I can't get my kyve coins back because I don't have tkyve in my hand. Can you help me?

**Comment by liangping** [comment]
@cecicece Sorry, I don't have either.

**Comment by cecicece** [comment]
So, how can I get back my clan kyves inside? is there no other way?

**Comment by liangping** [comment]
> So, how can I get back my clan kyves inside? is there no other way?

I know nothing about `kyves`.  really don't know how to help you.
