### ISSUE TITLE
display sdk, tendermint, ibc-go versions in the explorer

### ISSUE THREAD

**Issue by charleenfei** [ping-pub/explorer#181]
there are already many useful items displayed in the explorer. however, depending on the target audience of this explorer, it could be useful to query for the sdk, tendermint, and ibc-go versions from the `/cosmos/base/tendermint/v1beta1/node_info` endpoint so that devs around the interchain can see which versions are deployed on mainnet (and therefore, what cross-version interactions might be happening)

thank you for this contribution to the ecosystem so far!

**Comment by liangping** [comment]
Actually, It shows on the first version. however, many projects disabled this api for security consideration.

**Comment by charleenfei** [comment]
ah, got it. thanks for that!

**Comment by liangping** [comment]
I will try to re-implement the `home` and `parameters` page.

**Comment by liangping** [comment]
added. https://ping.pub/cosmos/parameters

**Comment by charleenfei** [comment]
amazing!! tysm!
