### ISSUE TITLE
recent transactions view (feature request)

### ISSUE THREAD

**Issue by dckc** [ping-pub/explorer#189]
great stuff! I/we use this thing all the time...

We can sometimes find recent transactions from recent blocks, but when the chain has been idle for a long time, it's a pain.

I'd really like a recent transactions view, similar to https://agoric.bigdipper.live/transactions

Is that feasible without an off-chain database index?

**Comment by liangping** [comment]
It's possible, but will produce heavy resource consumed on RPC server.

**Comment by liangping** [comment]
Added. https://github.com/ping-pub/explorer/commit/07bd6ee4b19eeb83880c42f7cfcbb8e7f7c401b1

**Comment by liangping** [comment]
https://ping.pub/cosmos/blocks

**Comment by dckc** [comment]
Wow! Thanks!

cc @arirubinstein
