### ISSUE TITLE
Incorrect reward amount displayed on all chains

### ISSUE THREAD

**Issue by qf3l3k** [ping-pub/explorer#198]
Seems that reward parameter in UI doesn't calculate reward correctly.
It shows too big rewards. Initially thought might be multiplied by 1000, but it seems this is not exactly multiplier of 1000.
Commission has correct value.

![image](https://user-images.githubusercontent.com/36550920/189538571-528b802e-a523-45d2-8e93-7538f6fb2d9b.png)

here is same validator from montscan
![image](https://user-images.githubusercontent.com/36550920/189542455-9697c15d-0d53-4bf6-9c8e-4d5eb975325b.png)

**Comment by liangping** [comment]
Hello, This value has changed from validator's self-bonded rewards to validator's outstanding rewards(all rewards from all delegators)
if you want to see self-bonded rewards, you can click the address in the right panel.

**Comment by qf3l3k** [comment]
ah, that would explain why amount was so random across chains.
thank you for clarification!
