### ISSUE TITLE
v0.46.1 Governance not supported

### ISSUE THREAD

**Issue by mbreithecker** [ping-pub/explorer#217]
Hi, in the new Cosmos version they changed the entire governance.
New proposals have a completely new schema. Also the query URLs changed from `/cosmos/gov/v1beta1/...` to `/cosmos/gov/v1/...` (src/libs/fetch.js) 
Right now, ping crashes when loading the governance page with mixed proposals (v0.45 and v0.46). It tries to access `content` which is `null` now.

**Comment by liangping** [comment]
Which chain?  osmosis v12.0.0 use v0.46.1, it has no problem

**Comment by johnletey** [comment]
Hey @liangping 👋🏻  Looks like Osmosis is replacing the Cosmos SDK dependency (v0.46.1) with their custom fork (v0.45.1).

https://github.com/osmosis-labs/osmosis/blob/main/go.mod#L297

**Comment by liangping** [comment]
ok, then on which chain I can reproduce?

**Comment by mbreithecker** [comment]
On our beta network:

Explorer: https://explorer.beta.kyve.network/
API: https://api.beta.kyve.network

**Comment by liangping** [comment]
Hmm, Interesting, seems no place to get more detail

**Comment by johnletey** [comment]
@liangping Was also wondering what the schema for `metadata` would be.

Looks like they have a schema public [here](https://docs.cosmos.network/main/modules/gov#proposal-3).
Looks like it will point to IPFS (or, in our case, we'll use Arweave).

**Comment by liangping** [comment]
> On our beta network:
> 
> Explorer: https://explorer.beta.kyve.network/kyve-betanet/gov API: https://api.beta.kyve.network

@mbreithecker I am looking at swagger api, but I did not found the gov api docs. 

Or any of you guys know how to get metadata from REST api?

**Comment by mbreithecker** [comment]
For some reason they removed a lot of stuff from the swagger API.

All queries can be found in the proto file:
https://github.com/cosmos/cosmos-sdk/blob/252c6736161e51342bb7dd6af984082a2b064742/proto/cosmos/gov/v1/query.proto

E.g.:
https://api.beta.kyve.network/cosmos/gov/v1/proposals/21
(metadata is at the bottom, for this proposal we just put a simple descriptive string in it.)

**Comment by liangping** [comment]
I was unable to found the metadata on either query.proto or your swagger api.

**Comment by mbreithecker** [comment]
https://api.beta.kyve.network/cosmos/gov/v1/proposals/21

This one returns a field "metadata" for me. 
Are you using the old "v1beta1" queries? Because for these content is null. 
But you need to use the "v1" queries.

And here is an old proposal which was created with v0.45 https://api.beta.kyve.network/cosmos/gov/v1/proposals/20
Here "metadata" is empty.

**Comment by liangping** [comment]
```json
{
  "proposal": {
    "id": "21",
    "messages": [
      {
        "@type": "/kyve.fees.v1beta1.MsgUpdateParams",
        "authority": "kyve10d07y265gmmuvt4z0w9aw880jnsr700jdv7nah",
        "payload": "{\n  \"min_gas_price\": \"1\",\n  \"burn_ratio\": \"0.5\",\n  \"min_initial_deposit_ratio\": \"0.5\"\n}"
      }
    ],
    "status": "PROPOSAL_STATUS_PASSED",
    "final_tally_result": {
      "yes_count": "5020299768120000",
      "abstain_count": "0",
      "no_count": "0",
      "no_with_veto_count": "9000000000000"
    },
    "submit_time": "2022-10-07T13:59:18.296181741Z",
    "deposit_end_time": "2022-10-07T19:59:18.296181741Z",
    "total_deposit": [
      {
        "denom": "tkyve",
        "amount": "20000000000000"
      }
    ],
    "voting_start_time": "2022-10-07T13:59:18.296181741Z",
    "voting_end_time": "2022-10-07T19:59:18.296181741Z",
    "metadata": "Update fee params"
  }
}
```

The problem is that we have to get more information from this` "metadata": "Update fee params"` 

Otherwise, there's no human readable information.

**Comment by liangping** [comment]
Ok, I pushed a patch, which will parse title/description from metadata. 

Please let me know if it's any issues.

**Comment by liangping** [comment]
https://github.com/ping-pub/explorer/commit/e0a008b4662ee39e29c553462de9f3e4f0065cdc

**Comment by mbreithecker** [comment]
Thanks for the commit.
But there are still some things which dont seem right.
I pulled the latest changes from master and deployed them.

So gov overview page is still empty:
https://explorer.beta.kyve.network/kyve-betanet/gov

Old proposals seem to be fine:
https://explorer.beta.kyve.network/kyve-betanet/gov/23

Current proposals still look weird:
https://explorer.beta.kyve.network/kyve-betanet/gov/24
(see attachment, as voting time on the beta network is only 6h)

![Screenshot 2022-10-25 at 21 01 52](https://user-images.githubusercontent.com/72022235/197859572-e8a978ab-311a-4a51-9ed5-3c335defa9db.png)

**Comment by liangping** [comment]
```
{
  "proposal_id": "24",
  "content": null,
  "status": "PROPOSAL_STATUS_REJECTED",
  "final_tally_result": {
    "yes": "116822658595820",
    "abstain": "0",
    "no": "10009113000000000",
    "no_with_veto": "0"
  },
  "submit_time": "2022-10-25T15:12:37.471670166Z",
  "deposit_end_time": "2022-10-25T21:12:37.471670166Z",
  "total_deposit": [
    {
      "denom": "tkyve",
      "amount": "20000010000000"
    }
  ],
  "voting_start_time": "2022-10-25T15:12:37.471670166Z",
  "voting_end_time": "2022-10-25T21:12:37.471670166Z"
}
```

You have to have either `content` or 'metadata',

and the metadata must meet the suggestion of the specification where defines the structure to be parsed.

**Comment by mbreithecker** [comment]
Looking at the network tab, it queries: https://api.beta.kyve.network/cosmos/gov/v1beta1/proposals?pagination.reverse=true

I think this is the code: https://github.com/ping-pub/explorer/blob/master/src/libs/fetch.js#L267-L293

But for the new governance it needs to query https://api.beta.kyve.network/cosmos/gov/v1/proposals?pagination.reverse=true

with `v1` instead of `v1beta1`

Regarding the metdadata: Technically everybody can do a proposal and write any arbitrary string in it. Is it possible to add a fallback strategy for this? For example just displaying the raw metadata-string?

**Comment by freak12techno** [comment]
Adding an example to easy reproduce it: https://ping.pub/quicksilver/gov

This page queries the v1beta1 proposals instead of v1, which fails with `codespace sdk code 29: invalid type: can't convert a gov/v1 Proposal to gov/v1beta1 Proposal when amount of proposal messages not exactly one`.

**Comment by liangping** [comment]
fixed it
