### ISSUE TITLE
Transaction search failed

### ISSUE THREAD

**Issue by nodestake** [ping-pub/explorer#266]
If there are a large number of transactions in a single tx, it cannot be displayed in Transactions.
The issue happened after the upgrade of the commit(de3ac8e7094740b00b291ab8f1a172f6c4744d72)

For example:
Evmos tx:1E23360E393179B42980FF7BA58F08A6A16741BB3267CA9FAA30A800E6EC4FE9
It will be stuck when we open the page: https://ping.pub/evmos/tx/1E23360E393179B42980FF7BA58F08A6A16741BB3267CA9FAA30A800E6EC4FE9
It is ok on https://www.mintscan.io/evmos/txs/1E23360E393179B42980FF7BA58F08A6A16741BB3267CA9FAA30A800E6EC4FE9

**Comment by liangping** [comment]
@nodestake It's because this tx is too big, exceeds this maximum size of grpc size. so nothing is returned from the endpoint. 
This is an edge case.
