### ISSUE TITLE
Swagger API does not match in Cosmos SDK v0.46.3

### ISSUE THREAD

**Issue by Sirius198** [ping-pub/explorer#276]
/src/libs/fetch.js getBankTotal(denom)

The current project used this command to fetch total supply by denom
`
return this.get('/cosmos/bank/v1beta1/supply/${denom}').then(data => commonProcess(data).amount)
`
but in v0.46.3, I probably use this url to fetch token amount
`
return this.get('/cosmos/bank/v1beta1/supply/by_denom?denom=${denom}').then(data => commonProcess(data).amount)
`

I think there should be one more condition to work in upgraded versions like below.

```
async getBankTotal(denom) {
    if (compareVersions(this.config.sdk_version, '0.40') < 0) {
      return this.get('/supply/total/${denom}').then(data => ({ amount: commonProcess(data), denom }))
    }
    if (compareVersions(this.config.sdk_version, '0.46') < 0) {
    return this.get('/cosmos/bank/v1beta1/supply/${denom}').then(data => commonProcess(data).amount)
    }
    return this.get('/cosmos/bank/v1beta1/supply/by_denom?denom=${denom}').then(data => commonProcess(data).amount)
  }
```

**Comment by Sirius198** [comment]
@liangping 
So what should I do whenever I want to make a PR?
Would you like to make a change like above?

**Comment by liangping** [comment]
yes, please!
