### ISSUE TITLE
Enable Keplr - In the connect wallet does not work

### ISSUE THREAD

**Issue by effofxprime** [ping-pub/explorer#284]
When trying to use the explorer to add a chain to your Keplr wallet, going to the `connect wallet` and trying to use the `Enable Keplr` button does not work.

The error is : `Error: "stakeCurrency.coinDecimals" must be a number`

I tested out a few things in a browser console and the issue appears to be the quotes surrounding everything.

**Comment by effofxprime** [comment]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/53557/206923736-24af1c71-bf9c-48ec-92d2-f0d8b0e4a5fb.png">
Once I removed the surrounding quotes, I got a new error.  That keys value is also in quotes, which seems to be the problem.

**Comment by effofxprime** [comment]
FWIW, I've found a possible way to easily replace the function.  https://www.npmjs.com/package/json5

https://json5.org/

**Comment by liangping** [comment]
patched.
