### ISSUE TITLE
Feature for custom configuration of delegation APR on the chain

### ISSUE THREAD

**Issue by gophereth** [ping-pub/explorer#293]
It would be nice to provide an interface so that team can feed APR information on the explorer rather than just assuming Cosmos native mint module.
Several teams are using custom API endpoints for APR display.

**Comment by freedumb2001** [comment]
That would be of great utility!

**Comment by liangping** [comment]
We didn't have good support on customization, That's one of main goals on next version, We will allow project to custom any api.

**Comment by liangping** [comment]
This is a example that how you can implement it
https://github.com/ping-pub/explorer/blob/master/src/libs/clients/evmos.ts
