### ISSUE TITLE
Jackal Testnet Page Stopped Working

### ISSUE THREAD

**Issue by TheMarstonConnell** [ping-pub/explorer#310]
One day the [Jackal Testnet Page](https://testnet.ping.pub/jackal) just stopped working, no upgrade was done to the RPC node.

This is the network tab showing the get request failed:
![image](https://user-images.githubusercontent.com/34043723/215158640-09fb37f6-0d48-4cf4-a56d-f22515514c61.png)
![image](https://user-images.githubusercontent.com/34043723/215158679-534b450e-64fe-44c0-8c19-a00dd2816039.png)

But here is the link and it is fine, we've tested it on other local versions of the explorer and it works fine. Not sure what's going on here.
https://testnet-api.jackalprotocol.com/cosmos/base/tendermint/v1beta1/blocks/latest

Thanks

**Comment by effofxprime** [comment]
Marston, this looks to be a CORS issue.
<img width="944" alt="image" src="https://user-images.githubusercontent.com/53557/219982756-cca212a6-f4d1-4fee-ab5d-88cd4f034725.png">

On the testnet RPC/API server, you will need to do one of the following:  Specifically, allow the domains you want to access the RPC/API, or you can set it to a wildcard.
Feel free to hit me up on discord (Erialos | The Silver Fox) if you need help resolving it.
