### ISSUE TITLE
Show jailed status for inactive validators

### ISSUE THREAD

**Issue by webmaster128** [ping-pub/explorer#339]
Hi Sir! Great explorer project, love it.

We often have changes between acrtive and inactive validators in our testnet. However, the first few inactives ones are jailed. Since this is not visible in page, it is hard to tell which validator becomes active next.

Here you have an example where I marked the jailed ones. So in reality position 6 and 7 should get ready, which they don't easily see.

<img width="1274" alt="Bildschirm­foto 2023-03-03 um 14 19 57" src="https://user-images.githubusercontent.com/2603011/222730855-9ebb667a-35e9-4da0-b4c7-bb7a4be43d71.png">

**Comment by liangping** [comment]
Ok, will do this on next version

**Comment by liangping** [comment]
@webmaster128 added. 

We also add wasm module for developers, wondering when will we have metadata of wasm contract. therefore we can provide more rich operations for a smart contract.
