### ISSUE TITLE
CUDOS Testnet not working, but CUDOS mainnet working perfectly

### ISSUE THREAD

**Issue by admcudo** [ping-pub/explorer#340]
This is a most confusing issue.

The two REST servers:
- https://rest.cudos.org/
- https://rest.testnet.cudos.org/
Are configured all but identically. They're both fronted by Cloudflare, through an stunnel TLS processor and into the REST port on the node.

Despite this, the testnet explorer is empty where the mainnet one works a treat.

I am seeing error messages like:

"Access to fetch at 'https://rest.testnet.cudos.org/ibc/apps/transfer/v1/denom_traces?pagination.limit=500' from origin 'https://testnet.ping.pub' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

"Access to fetch at 'https://rest.testnet.cudos.org/cosmos/base/tendermint/v1beta1/blocks/latest' from origin 'https://testnet.ping.pub' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

The CORS settings in both nodes (main and test) are the same: "*"
.. So there shouldn't be a CORS issue with the testnet server in the same way that there isn't an issue with the mainnet server.

**Comment by liangping** [comment]
I checked your response header, and CORS did not setup correctly
