### ISSUE TITLE
Unable to stake Lambda(Evmos base chain) on ping.pub

### ISSUE THREAD

**Issue by iwbinb** [ping-pub/explorer#353]
https://ping.pub/lambda/staking
Lambda chain is an Evmos fork chain, when I want to stake LAMB on ping.pub, it says "pubKey does not match signer address".
I remember ping.pub support the evmos fork chains before, why it is unable now?

**Comment by liangping** [comment]
There's some special configs(such as algo) for ethermint chains, you can just simply copy to your chain config.
