### ISSUE TITLE
Keplr not working with genesisL1 chain and Evmos

### ISSUE THREAD

**Issue by alpha-omega-labs** [ping-pub/explorer#39]
Hello,
Thank you for such a perfect app!
There is an error when doing and tx with ping pub and Keplr:

<code>TypeError: Cannot read property 'toString' of undefined</code>

Thank you

**Comment by alpha-omega-labs** [comment]
Please, add genesisL1 mainnet support:

{
    "chain_name": "genesisL1",
    "coingecko": "genesisL1",
    "api": "https://api.genesisl1.org",
    "sdk_version": "0.42.4",
    "addr_prefix": "genesis",
    "logo": "https://raw.githubusercontent.com/alpha-omega-labs/bashscripts/main/genesisl1.png"
}

decimals: 18
power reduction: 18 
coin: L1
mint: aphoton
thank you.

**Comment by liangping** [comment]
OK

**Comment by liangping** [comment]
> Hello,
> Thank you for such a perfect app!
> There is an error when doing and tx with ping pub and Keplr:
> 
> <code>TypeError: Cannot read property 'toString' of undefined</code>
> 
> Thank you
> 

Keplr does  not support your chain

**Comment by liangping** [comment]
> Please, add genesisL1 mainnet support:
> 
> {
>     "chain_name": "genesisL1",
>     "coingecko": "genesisL1",
>     "api": "https://api.genesisl1.org",
>     "sdk_version": "0.42.4",
>     "addr_prefix": "genesis",
>     "logo": "https://raw.githubusercontent.com/alpha-omega-labs/bashscripts/main/genesisl1.png"
> }
> 
> decimals: 18
> power reduction: 18 
> coin: L1
> mint: aphoton
> thank you.

added, but please invite more indenpent validators.

**Comment by alpha-omega-labs** [comment]
Thank you! We are very new and new validators are coming! Please, consider accepting L1 gift!
keplr.genesisl1.org for keplr add
And it seems like that added chain is a bit wrong (its connected to evmos)
genesisL1 is evmos fork and .evmosd binary name stay, but network is different.

**Comment by liangping** [comment]
> Thank you! We are very new and new validators are coming! Please, consider accepting L1 gift! keplr.genesisl1.org for keplr 

I know how it implement, but seems it's heavy for a mutli-chain explorer. 

> add And it seems like that added chain is a bit wrong (its connected to evmos) genesisL1 is evmos fork and .evmosd binary name stay, but network is different.

It's not connected evmos, we haven't added evmos on mainnet so far.  All data is fetched from the api you provided `https://api.genesisl1.org`. 

Let me know what exactly is wrong?  Could you please join our Discord community to discus.
