### ISSUE TITLE
No More Search-bar?

### ISSUE THREAD

**Issue by TheMarstonConnell** [ping-pub/explorer#392]
<img width="1080" alt="image" src="https://github.com/ping-pub/explorer/assets/34043723/7e355398-86c3-46a6-ae2d-95a9170491df">

On the old ping.pub dashboard we got a search bar to search for Txns and accounts, but now that functionality seems to be removed. I can't find a replacement for the search bar. Is there anything I'm missing or is the search bar truly gone?

**Comment by liangping** [comment]
Will add soon.

**Comment by nodeiistt** [comment]
The new interface is quite successful. Congratulations!

**Comment by liangping** [comment]
Fixed.
