### ISSUE TITLE
New version has no consensus monitor

### ISSUE THREAD

**Issue by LexaMichaelides** [ping-pub/explorer#415]
Any plans to add this back (like the search bar)? This was a really key tool for Replicated Security chain launches.

**Comment by liangping** [comment]
OK.  I thought not many people use it.

**Comment by liangping** [comment]
`like the search bar` We are going to build a advance search bar. but maybe we can add a simple one first

**Comment by liangping** [comment]
@LexaMichaelides Hey.  both consensus and seach are back. 

By the way,  could you provide more endpoints for neutrong?
