### ISSUE TITLE
Add back "❤️ Helping xxxValidator by Staking ❤️" in the New Version

### ISSUE THREAD

**Issue by iwbinb** [ping-pub/explorer#429]
The old version of PingPub has "❤️ Helping xxxValidator by Staking ❤️ "and becomes the most popular Explorer in the Cosmos ecosystem.
Please add back this feature in the new version of PingPub.
Most of Cosmos Validators are not profitable. The commission they earns may not be enough to run the server cost of Validator, Explorer, Endpoints. So please add this feature in the new version of Pinghub. Let the new PingPub become the most popular open source Explorer again, and also supports the validators who are running Explorer.

**Comment by liangping** [comment]
We are planning to create delegate widget. so validators can add the widget to their own website. Users can deposit to their validator on its website.

**Comment by iwbinb** [comment]
That feature sounds good.
But it is another thing, when the validators run the explorer, they hope users can support their validator with a easy way.

**Comment by iwbinb** [comment]
That feature sounds good.
But it is another thing, when the validators run the explorer, they hope users can support their validator with a easy way.
If it's not too difficult, we'd still like to add that feature back

**Comment by iwbinb** [comment]
Ping Explorer is the most popular Explorer and Staking Tool of the Cosmos SDK chains. Not only because it is open source, but it can also bring some convenience to the validators and their communities.
So be sure to recover this function, and ping v2 will be used by more people again.
Restoring this function will not bring bad.

**Comment by liangping** [comment]
The reason is that we are thinking to show staking parameter(Such as APR, Unbonding Period and other tips) on the top of the validator list.

**Comment by iwbinb** [comment]
Yes. You can mark those validators as those who provide RPC/API or Snapshot and make their rankings on the top. 
Their infrastructure services are very important in the ecosystem. It is worth making users pay more attention to them.
Adding back "❤️ Helping xxxvalidator by Staking ❤️" function is also good, that will make more validators more motivation to run the Ping V2 Explorer.

**Comment by nodestake** [comment]
We support to Add back "❤️ Helping xxxValidator by Staking ❤️" in the New Version

**Comment by liangping** [comment]
added a popular tab for all endpoint providers.
