### ISSUE TITLE
Update each validator's signing info on a new block

### ISSUE THREAD

**Issue by freak12techno** [ping-pub/explorer#447]
The explorer currently fetches signing-infos of all validators only once, and then does not update it when the new blocks are coming.
Is it possible to fetch signing-infos when a new block is populated and update all validators' missed blocks counter? That should display it in a bit more accurate way.

**Comment by liangping** [comment]
will update missing blocks at fixed height. such as `height`% 100 = 0

**Comment by liangping** [comment]
fixed: https://github.com/ping-pub/explorer/commit/ad1055d1917a1c9a4c1e042ec25c399881a90c86
