### ISSUE TITLE
PingPub doesn't handle gov proposals from Cosmos SDK v0.46 chains

### ISSUE THREAD

**Issue by robert-zaremba** [ping-pub/explorer#473]
At Umee we are proudly using PingPub in our testnet.
However, since full migration to v0.46 metadata, the ping pub doesn't display any more proposals correctly. I've also noticed that the same problem exists in Crypto.org chain. Examples:
* https://ping.pub/umee/gov/90
* https://ping.pub/crypto-com-chain/gov/16

Moreover listing all proposals for Umee fails: https://ping.pub/umee/gov

The proper way to handle title and description for v0.46 Cosmos chains is to parse Metadata, which is expected to be:
* either a link to external JSON resource
* JSON string
In both cases, JSON should contain both `title` and `summary` as described in the [documentation](https://github.com/cosmos/cosmos-sdk/tree/main/x/gov#metadata).

The Cosmos SDK v0.47 set those fields back in the [Proposal](https://github.com/cosmos/cosmos-sdk/blob/v0.47.3/proto/cosmos/gov/v1/gov.proto#L88) type as all proposals should have them set anyway.

The strategy we recommended is (pseudocode):
```
if proposal.title != unknown {
   return (proposal.title, proposal.summary, null)
}
var metadataStr = proposal.metadata
if proposal.meteadata is url {
  metadataStr = string(fetch(proposal.metadata))
}
metadata, err = JSON.parse(metadataStr)
if err != null {
  return ("","", err)
}
return (metadata.title, metadata.summary, null)
```

**Comment by liangping** [comment]
Thanks, we just need update sdk version in the chain config.

**Comment by liangping** [comment]
> var metadataStr = proposal.metadata
> if proposal.meteadata is url {
>   metadataStr = string(fetch(proposal.metadata))
> }

this is not possible, since there are CROS restriction

**Comment by liangping** [comment]
that is all we need

**Comment by liangping** [comment]
<img width="1885" alt="image" src="https://github.com/ping-pub/explorer/assets/2882920/445bf565-5155-4d4f-8557-01cec9c48fd8">
I don't see any abnormal if you selected a right endpoint. (some endpoints are not stable sometimes)

**Comment by liangping** [comment]
Let me know if you still have issue
