### ISSUE TITLE
Issue in viewing contract transactions detail

### ISSUE THREAD

**Issue by ahmad-blocksdev** [ping-pub/explorer#488]
First, Transactions are only showing for Osmosis network, not working for all. 
Second, for Osmosis, there is a hard coded address, which is showing same transactions for all contract address because
of a hard coded address in the transactions.vue file on Line 13:
`const address = "osmo1yg8930mj8pk288lmkjex0qz85mj8wgtns5uzwyn2hs25pwdnw42sf745wc" `

**Comment by liangping** [comment]
fixed
