### ISSUE TITLE
On params change proposals, show the current value together with the suggested one

### ISSUE THREAD

**Issue by freak12techno** [ping-pub/explorer#508]
Real-life example: see the proposal I submitted today: https://ping.pub/decentr/gov/28
It shows that it proposes to change the SignedBlocksWindow to 20,000 but it doesn't show which value is used on chain right now.
The current value in use can be fetched from LCD endpoint in the following way or similar: https://rest.mainnet.decentr.xyz/cosmos/params/v1beta1/params?subspace=slashing&key=SignedBlocksWindow

Here's how it may be useful:
There was a proposal aiming to decrease Cosmos Hub's max block size from 21M to 1M: https://ping.pub/cosmos/gov/827, while the current on-chain param was set to 200k or similar. Without this knowledge it would be easy to vote yes for the proposal as it's a no-brainer, but if you know the current on-chain value, you are better informed and can see that this proposal is in fact misleading in its title and you can make a better weighted decision.

**Comment by liangping** [comment]
implemented in https://github.com/ping-pub/explorer/commit/21ff37aac182966a4e573e03355a2085049e31ba
