### ISSUE TITLE
"NaN OSMO" on Sentinel's validator on "Commissions and rewards" page

### ISSUE THREAD

**Issue by freak12techno** [ping-pub/explorer#509]
The title should be self-explanatory, see the screenshot:
<img width="334" alt="image" src="https://github.com/ping-pub/explorer/assets/83376337/98fa7cc6-d094-4da2-a0a9-7e985a4afc7f">
Seeing it on my validator's page: https://ping.pub/sentinel/staking/sentvaloper1rw9wtyhsus7jvx55v3qv5nzun054ma6kz4237k

**Comment by liangping** [comment]
fixed:
