### ISSUE TITLE
Pingpub is empty  behing dns alias

### ISSUE THREAD

**Issue by AlexanderNtk** [ping-pub/explorer#511]
We have PingPub instance working on EC2. It shared to internet via AWS lb. 
Ping pub compiled staticaly and distributed by nginx.
If I connect to lb link it works fine and display data.
If I connect to DNS alias It shows 0 chains.  It does not send XHR requests even.

**Comment by AlexanderNtk** [comment]
Documentation should be improved. 
Please add in documentation - If domain contains testnet in ANY part, then config would be used from testnet folder.
That's why in out case LB works fine, but alias with testnet was broken.

**Comment by liangping** [comment]
testnet configs is enabled by using a domain startswith `testnet`, such as `testnet.YOURNAME.COM`, `testnet.ping.pub`

**Comment by AlexanderNtk** [comment]
no. In our case we have blockexplorer.testnet.domain.io and load was from testnet folder.
In `src/stores/useDashboard.ts` is following `if(window.location.hostname.search("testnet") > -1)` it just search testnet.
