### ISSUE TITLE
State Sync section does not show height if loaded directly

### ISSUE THREAD

**Issue by migueldingli1997** [ping-pub/explorer#515]
If I open https://ping.pub/cosmos and then navigate to the State Sync section, then the height and hash values are populated:

<img width="1191" alt="image" src="https://github.com/ping-pub/explorer/assets/23614954/4fc0147e-160a-4906-9632-c02ceddd3cdb">

However, if I open the State Sync section directly https://ping.pub/cosmos/statesync, these values are zero and blank respectively:

<img width="1191" alt="image" src="https://github.com/ping-pub/explorer/assets/23614954/53ea4932-b4c1-4ce4-98ba-903e8adae70a">

Judging from console logs, there seems to be a call to `/cosmos/base/tendermint/v1beta1/blocks/0` that is erroring in the second case.

**Comment by liangping** [comment]
Thanks @migueldingli1997 , fixed.
