### ISSUE TITLE
Persistent cache for Keybase avatars

### ISSUE THREAD

**Issue by zenodeapp** [ping-pub/explorer#516]
Hi!

I noticed upon changing the avatar of a Keybase profile, ping pub keeps looking for the older url of the picture. I was looking in the code and saw that this is due to always using the stored value in the localStorage.

There are two ways this could be improved:
1. Either an expiration date is made in the cache, so that it refetches when the cache expires, or
2. It tries to refetch the avatar URL via the Keybase API if it fails to load the image. There are ways to implement this since an old avatar will show as a broken image and has a 403 Forbidden error if it's being queried. This error could be caught.

I could help implementing it! I'm only not used to using Vue, but could if you'd like that :).

**Comment by liangping** [comment]
We cached on your local browser for reducing overload of avatars. 

but seems that there should a have strategy for refresh the avatar. I am wondering if we could refresh the latest avatar in the validator page.

**Comment by zenodeapp** [comment]
> We cached on your local browser for reducing overload of avatars.
> 
> but seems that there should a have strategy for refresh the avatar. I am wondering if we could refresh the latest avatar in the validator page.

Aah that's also an idea and probably simplest! Like a refresh button that people can press to refresh the local stored avatar data for the validator?
