### ISSUE TITLE
On validators, list, "24h Changes" tab isn't populated if visiting page directly and not via SPA transition

### ISSUE THREAD

**Issue by freak12techno** [ping-pub/explorer#529]
This function https://github.com/ping-pub/explorer/blob/30826a0ed6a6b73d26989773332f5c3c32a47310/src/modules/%5Bchain%5D/staking/index.vue#L43C16-L43C27 isn't executed correctly if refreshing the page or visiting it directly, as staking.validators isn't set correctly so its .length === 0 so this function would do nothing. It'll populate it if you go to any other page and then back to it, but not if it's the first page you load.

How to reproduce:
1. Open the Staking tab
2. Reload the page
3. 24h changes tab is empty
4. Go to any other tab, then back to Staking tab
5. 24h changes tab is populated

**Comment by liangping** [comment]
fixed

**Comment by freak12techno** [comment]
@liangping I still see this behaviour somehow, both on my own explorer instance built from latest commits and on ping.pub, can you check if it was fixed? I can provide steps to reproduce it if needed
