### ISSUE TITLE
Proposal page won't load for CancelSoftwareUpgradeProposal

### ISSUE THREAD

**Issue by freak12techno** [ping-pub/explorer#530]
When opening such a proposal, the page gets stuck and nothing is displayed:
<img width="911" alt="image" src="https://github.com/ping-pub/explorer/assets/83376337/98089c0a-6e66-478b-8d00-2585d3c534e1">
And the console window shows the following error:
<img width="717" alt="image" src="https://github.com/ping-pub/explorer/assets/83376337/7c92c091-c4c8-4b34-9e68-343a6af2e0fd">

**Comment by liangping** [comment]
Currently，There are two versions of gov api. change your sdk_version to v0.47+ .
