### ISSUE TITLE
On staking page, 24h changes is displayed incorrectly if the denom returned by Tendermint isn't the same as display denom

### ISSUE THREAD

**Issue by freak12techno** [ping-pub/explorer#539]
On staking page, the validator's voting power is taken from the /validators endpoint that's provided by cosmos-sdk, and it's treated as a base denom converted to display denom (e.g. on Cosmos Hub, if a validator has 10000000uatom of delegations, it'll be displayed as 10 ATOM), but 24h changes values are taken from /validatorsets endpoints (provided by Tendermint) and validators' voting power from these endpoints is considered to be in display denom (e.g. ATOM in Cosmos Hub).
This is true for most of the chains, but is not for some, namely, e-Money, it returns voting power in ungm instead of ngm as expected by the explorer, leading to 24h changes being 1 million times more than they actually are and making it somewhat misleading:
<img width="352" alt="image" src="https://github.com/ping-pub/explorer/assets/83376337/06cc56ce-5d4c-461e-8a34-64ba88375e4f">
I guess ideal solution would be to have this coefficient (by how much you need to divide the result of /validatorsets endpoint's voting power to get the tokens amount in display denom) in chain config, using 1 as a default everywhere to avoid specifying it for every chain, and allow overriding it there.

**Comment by liangping** [comment]
We strive to keep the configuration minimal, avoiding unnecessary additions. 

However, there are two areas that require improvement:

1. The amount is not accurate on some chains.
2. The time window assumes a block time of 6s, but many chains differ—for example, 1s on Injective and 500ms on DYDX.

**Comment by freak12techno** [comment]
> We strive to keep the configuration minimal, avoiding unnecessary additions.

any reasons why? problem is, some chains have these issues and it's better to be able to configure it rather than hardcoding these edge cases (like here https://github.com/ping-pub/explorer/blob/master/src/libs/address.ts#L25), what do you think?

anyways, I can update that to be passed from config by submitting a PR fixing this ssue, if you want

> The time window assumes a block time of 6s, but many chains differ—for example, 1s on Injective and 500ms on DYDX.
this also poses another issue btw - it's assumed that the block 24 hours ago was 14400 blocks ago, but it's not always true (like for examples above), do you think this is worth fixing as well?

**Comment by liangping** [comment]
@freak12techno would be better to add the prefix in the config rather than hardcode.  Do you want to submit a PR for it.

> this also poses another issue btw - it's assumed that the block 24 hours ago was 14400 blocks ago, but it's not always true (like for examples above), do you think this is worth fixing as well?

Will fix it, but not now.

**Comment by freak12techno** [comment]
Done.
