### ISSUE TITLE
Missing @cosmjs/amino

### ISSUE THREAD

**Issue by cougarmaster** [ping-pub/explorer#566]
Getting this error from fresh git clone

`transforming (818) node_modules/encode-utf8/index.jssrc/modules/[chain]/account/[address].vue:21:27 - error TS2307: Cannot find module '@cosmjs/amino' or its corresponding type declarations.

21 import type { Coin } from '@cosmjs/amino';
                             ~~~~~~~~~~~~~~~


Found 1 error in src/modules/[chain]/account/[address].vue:21

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "type-check" exited with 2.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by 0ndrec** [comment]
![4564565](https://github.com/ping-pub/explorer/assets/30905073/ef8322de-054a-4513-9e0c-f000911ac8e2)
same

**Comment by ngokhang66** [comment]
`npm i @cosmjs/amino --force `
for fix this error. up vote if it help u

**Comment by cougarmaster** [comment]
> `npm i @cosmjs/amino --force ` for fix this error. up vote if it help u

I got it off of a fork so I will try it on another server.

**Comment by 0ndrec** [comment]
> Same here. Add it to `package.json`:
> ```
> "dependencies": {
>   ...
>   "@cosmjs/amino": "^0.32.3",
>   ...
> ```
> And it worked.

Thx bro

**Comment by liangping** [comment]
https://github.com/ping-pub/explorer/pull/567
