### ISSUE TITLE
Allow delegation to inactive set validators

### ISSUE THREAD

**Issue by Zygimantass** [ping-pub/explorer#65]
To support decentralization and allow newcomers into the space, it should be allowed to input a custom valoper instead of selecting the one in the list (when you click the delegate button). Right now if you do that, it says it can't find it in the list, and if you try going to it through the URL (for example https://ping.pub/osmosis/staking/osmovaloper1f3p3aakrx5z53cqha8utaw8hvjsq36yn7kg234), it shows up with invalid data.

**Comment by liangping** [comment]
@Zygimantass , Will fixed.

**Comment by liangping** [comment]
https://github.com/ping-pub/explorer/commit/3f0dcdf276bbab415e00e81095cc6117fd9a4876

Fixed @Zygimantass
